apiVersion: v1
data:
    DISCORD_APPLICATION_ID: ~omit
    DISCORD_BOT_TOKEN: ~omit
    DISCORD_PUBLICKEY: ~omit
kind: Secret
metadata:
    name: discord-dicebot
    namespace: comame-xyz
type: Opaque

