apiVersion: v1
kind: Namespace
metadata:
  name: clusterlog

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterlog
  namespace: clusterlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clusterlog
  template:
    metadata:
      labels:
        app: clusterlog
    spec:
      containers:
        - image: registry.comame.dev/log.cluster.comame.dev:latest
          name: clusterlog
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - secretRef:
                name: clusterlog
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: clusterlog
  namespace: clusterlog
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: clusterlog

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: clusterlog
spec:
  selector:
    matchLabels:
      name: log-collector
  template:
    metadata:
      labels:
        name: log-collector
    spec:
      containers:
        - name: log-collector
          image: registry.comame.dev/kube-log:latest
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/log/containers
              name: logdir
            - mountPath: /var/log/pods
              name: podlogdir
          envFrom:
            - secretRef:
                name: clusterlog
          env:
            - name: TZ
              value: Asia/Tokyo
      securityContext:
        runAsUser: 0
      volumes:
        - name: logdir
          hostPath:
            path: /var/log/containers
            type: Directory
        - name: podlogdir
          hostPath:
            path: /var/log/pods
            type: Directory
      imagePullSecrets:
        - name: regcred
