apiVersion: v1
kind: Namespace
metadata:
  name: ddns

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddns
  namespace: ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddns
  template:
    metadata:
      labels:
        app: ddns
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        # https://github.com/comame/CloudFlare-DDNS
        - image: registry.comame.dev/ddns
          name: ddns
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: env
                  key: api-token
            - name: CLOUDFLARE_ZONE_ID
              valueFrom:
                secretKeyRef:
                  name: env
                  key: zone-id
            - name: DOMAIN
              value: s1.comame.xyz
