apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - image: elasticsearch:8.5.1
          imagePullPolicy: IfNotPresent
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          env:
            - name: discovery.type
              value: single-node
            - name: cluster.name
              value: elasticsearch-comame-xyz
            - name: network.host
              value: 0.0.0.0
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: volume
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/elasticsearch

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: elasticsearch
  type: LoadBalancer
  loadBalancerIP: 192.168.0.162
