apiVersion: v1
kind: Namespace
metadata:
  name: id

---
# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: id
  namespace: id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id
  template:
    metadata:
      labels:
        app: id
    spec:
      containers:
        - image: registry.comame.dev/id:latest
          name: id
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - secretRef:
                name: id
      imagePullSecrets:
        - name: regcred

---
# Service

apiVersion: v1
kind: Service
metadata:
  name: id
  namespace: id
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: main
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: dash
  selector:
    app: id
