apiVersion: v1
kind: Namespace
metadata:
  name: livestream

---
# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestream
  namespace: livestream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestream
  template:
    metadata:
      labels:
        app: livestream
    spec:
      containers:
        - image: registry.comame.dev/livestream:latest
          name: livestream
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 1935
              protocol: TCP
      imagePullSecrets:
        - name: regcred

---
# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: livestream-viewer
  namespace: livestream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livestream-viewer
  template:
    metadata:
      labels:
        app: livestream-viewer
    spec:
      containers:
        - image: registry.comame.dev/livestream-viewer:latest
          name: livestream-viewer
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: regcred

---
# Service

apiVersion: v1
kind: Service
metadata:
  name: livestream-viewer
  namespace: livestream
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: livestream-viewer

---
# Service

apiVersion: v1
kind: Service
metadata:
  name: livestream-http
  namespace: livestream
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: livestream

---

apiVersion: v1
kind: Service
metadata:
  name: livestream-rtmp
  namespace: livestream
spec:
  ports:
    - port: 1935
      targetPort: 1935
      protocol: TCP
  selector:
    app: livestream
  type: LoadBalancer
  loadBalancerIP: 192.168.0.163
