apiVersion: v1
kind: Namespace
metadata:
  name: minecraft

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: registry.comame.dev/minecraft-server:1.10.2
          imagePullPolicy: IfNotPresent
          name: minecraft
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 25575
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user
              name: volume
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/minecraft

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-backup
  namespace: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft-backup
  template:
    metadata:
      labels:
        app: minecraft-backup
    spec:
      containers:
        - image: registry.comame.dev/minecraft-backup:latest
          name: minecraft-backup
          volumeMounts:
            - mountPath: /home/node/minecraft
              name: volume
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/minecraft

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: game
    - port: 25575
      targetPort: 25575
      protocol: TCP
      name: rcon
  selector:
    app: minecraft
  type: LoadBalancer
  loadBalancerIP: 192.168.0.150
