apiVersion: v1
kind: Namespace
metadata:
  name: minecraft

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        # https://github.com/comame/minecraft-server
        - image: registry.comame.dev/minecraft-server:1.20.1
          imagePullPolicy: IfNotPresent
          name: minecraft
          command:
            - /jre/bin/java
            - -Dlog4j2.formatMsgNoLookups=true
            - -Xmx6144M
            - -jar
            - /server.jar
            - nogui
          ports:
            - containerPort: 25565
              protocol: TCP
            - containerPort: 25575
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user
              name: volume
          resources:
            limits:
              cpu: 1.5
            requests:
              cpu: 0.5
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/minecraft-1.20.1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-backup
  namespace: minecraft
spec:
  replicas: 0
  selector:
    matchLabels:
      app: minecraft-backup
  template:
    metadata:
      labels:
        app: minecraft-backup
    spec:
      containers:
        # https://github.com/comame/minecraft-server-backup
        - image: registry.comame.dev/minecraft-backup:latest
          name: minecraft-backup
          volumeMounts:
            - mountPath: /home/node/minecraft
              name: volume
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/minecraft-1.20.1

---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: game
    - port: 25575
      targetPort: 25575
      protocol: TCP
      name: rcon
  selector:
    app: minecraft
  type: LoadBalancer
  loadBalancerIP: 192.168.0.150
