apiVersion: v1
kind: Namespace
metadata:
  name: minecraft

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - image: minecraft-server
          imagePullPolicy: Never
          name: minecraft
          ports:
            - containerPort: 25565
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user
              name: volume
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/minecraft

---

apiVersion: v1
kind: Service
metadata:
  name: minecraft
  namespace: minecraft
spec:
  ports:
    - port: 25565
      targetPort: 25565
      protocol: TCP
  selector:
    app: minecraft
  type: LoadBalancer
  loadBalancerIP: 192.168.0.150
