apiVersion: v1
kind: Namespace
metadata:
  name: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:15.4
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: volume
      volumes:
        - name: volume
          hostPath:
            path: /home/comame/postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
spec:
  ports:
   - port: 5432
     targetPort: 5432
     protocol: TCP
  selector:
    app: postgres
  type: LoadBalancer
  loadBalancerIP: 192.168.0.161
