apiVersion: v1
kind: Namespace
metadata:
  name: redash
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redash
  namespace: redash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redash
  template:
    metadata:
      labels:
        app: redash
    spec:
      containers:
        - &redash
          image: redash/redash:10.1.0.b50633
          envFrom:
            - configMapRef: { name: cm-env }
            - secretRef: { name: secret-redash }
          resources:
            limits:
              memory: 512Mi
          name: scheduler
          args: [ scheduler ]
        - <<: *redash
          name: server
          args: [ server ]
          ports:
            - containerPort: 5000
          env:
            - name: REDASH_WEB_WORKERS
              value: '1'
        - <<: *redash
          name: worker-scheduled
          args: [ worker ]
          env:
            - name: QUEUES
              value: scheduled_queries,schemas
            - name: WORKERS_COUNT
              value: '1'
        - <<: *redash
          name: worker-adhoc
          args: [ worker ]
          env:
            - name: QUEUES
              value: queries
            - name: WORKERS_COUNT
              value: '1'
        - <<: *redash
          name: worker-default
          args: [ worker ]
          env:
            - name: QUEUES
              value: periodic,emails,default
            - name: WORKERS_COUNT
              value: '1'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-env
  namespace: redash
data:
  REDASH_REDIS_URL: redis://redis.comame.dev:6379/0
  REDASH_DATABASE_URL: postgresql://postgres:root@postgres.comame.dev/redash

---
apiVersion: v1
kind: Service
metadata:
  name: redash
  namespace: redash
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: redash
