apiVersion: v1
kind: Namespace
metadata:
  name: secret-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-manager
  namespace: secret-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-manager
  template:
    metadata:
      labels:
        app: secret-manager
    spec:
      containers:
        - image: registry.comame.dev/secret-manager:latest
          name: secret-manager
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: KUBE_IGNORE_TLS_ERROR
              value: 'false'
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: secret-manager
  namespace: secret-manager
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: secret-manager
