apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot-haifuri
  namespace: comame-xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot-haifuri
  template:
    metadata:
      labels:
        app: discord-bot-haifuri
    spec:
      containers:
        - image: registry.comame.dev/discord-bot-haifuri:latest
          name: discord-bot-haifuri
          ports:
          - containerPort: 8080
            protocol: TCP
          envFrom:
            - secretRef:
                name: discordbot-haifuri
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: discordbot-haifuri
  namespace: comame-xyz
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: discord-bot-haifuri

---

apiVersion: v1
kind: Secret
metadata:
  name: discordbot-haifuri
  namespace: comame-xyz
type: Opaque
data: {}
