apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotfiles
  namespace: comame-xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotfiles
  template:
    metadata:
      labels:
        app: dotfiles
    spec:
      containers:
      - image: registry.comame.dev/dotfiles:latest
        name: dotfiles
        ports:
        - containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: dotfiles
  namespace: comame-xyz
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: dotfiles
