apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink
  namespace: comame-xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink
  template:
    metadata:
      labels:
        app: shortlink
    spec:
      containers:
        - image: registry.comame.dev/shortlink:latest
          name: shortlink
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: shortlink
  namespace: comame-xyz
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: shortlink
