apiVersion: batch/v1
kind: CronJob
metadata:
  name: bluearchive-twitter
  namespace: comame-xyz
spec:
  schedule: "*/15 * * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: bluearchive-twitter
              image: registry.comame.dev/twitter-scraper-bluearchive
              imagePullPolicy: Always
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred
