apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: web
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@comame.xyz
    privateKeySecretRef:
      name: letsencrypt

    solvers:
    - selector:
        dnsZones:
          - comame.dev
      dns01:
        cloudflare:
          email: mail@comame.xyz
          apiTokenSecretRef:
            name: cloudflare-apikey-comamedev
            key: api-token
    - selector:
        dnsZones:
          - comame.xyz
      dns01:
        cloudflare:
          email: mail@comame.xyz
          apiTokenSecretRef:
            name: cloudflare-apikey-comamexyz
            key: api-token
