apiVersion: v1
kind: Namespace
metadata:
  name: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:7.2.3
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
  type: LoadBalancer
  loadBalancerIP: 192.168.0.170
