apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-internal-controller
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-internal
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingress-internal
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: ingress-nginx
    spec:
      containers:
        - name: controller
          image: k8s.gcr.io/ingress-nginx/controller:v1.1.1
          args:
            - /nginx-ingress-controller
            - '--controller-class=k8s.io/internal-ingress-nginx'
            - '--ingress-class=k8s.io/internal-nginx'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      serviceAccountName: ingress-nginx
      serviceAccount: ingress-nginx

---

apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: internal
spec:
  controller: k8s.io/internal-ingress-nginx

---

apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: ingress-internal
  name: ingress-internal
  namespace: ingress-nginx
spec:
  loadBalancerIP: 192.168.0.190
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
  selector:
    app.kubernetes.io/name: ingress-internal
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
