apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
      - name: l2
        protocol: layer2
        addresses:
          - 192.168.0.150-192.168.0.200
        avoid-buggy-ips: true
