apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: comame-xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - image: registry.comame.dev/echo:latest
        name: echo
        ports:
        - containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: comame-xyz
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: echo
  ipFamilyPolicy: RequireDualStack
