# Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: itl-web
  namespace: comame-xyz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itl-web
  template:
    metadata:
      labels:
        app: itl-web
    spec:
      containers:
      # https://github.com/comame/itl-web
      - image: registry.comame.dev/itl-web:latest
        name: itl-web
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: /root/.ar
            name: artworks
        env:
          - name: SMB_HOST
            value: d1.comame.dev:445
          - name: SMB_USER
            value: read-itunes
          - name: SMB_PASSWORD
            value: read-itunes
          - name: SMB_SHARENAME
            value: iTunes
          - name: ITUNES_LOCATION_PREFIX
            value: file://localhost/C:/Users/comame/Music/iTunes
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: artworks
          hostPath:
            path: /home/comame/itl-web-artwork

---

# Service

apiVersion: v1
kind: Service
metadata:
  name: itl-web
  namespace: comame-xyz
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: itl-web
